services:
  tempestapp:
    build:
      context: .
      dockerfile: ./builder/Dockerfile
    container_name: tempestapp
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./tempestsapp:/var/www
      - ./configs/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - traefik

  tempestweb:
    image: nginx:alpine
    container_name: tempestweb
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - "8021:80"
    volumes:
      - ./tempestsapp:/var/www
      - ./configs/default.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tempestapp.rule=Host(`ztempest.com`)"
      - "traefik.http.routers.tempestapp.entrypoints=web"
    networks:
      - traefik
    depends_on:
      - tempestapp

networks:
  traefik:
    external: true
